spring:
  config:
    activate:
      on-profile:
        - local
  data:
    mongodb:
      uri: mongodb+srv://amadeus:<password>@lag3r.vvr8lmd.mongodb.net/?retryWrites=true&w=majority
      database: local

---
logging: debug
